from django.contrib import admin
from .models import CustomUser, ForumQuestion, Tag, Quiz, QuizQuestion, RateQuiz, QuizQuestionChoice, TakeQuiz, UserAnswer, QuizQuestionHint, Achievement, UserAchievement, ForumAnswer, ForumBookmark, ForumUpvote, ForumDownvote, ForumAnswerUpvote, ForumAnswerDownvote, Follow, Block
# Register your models here.
admin.site.register(CustomUser)
admin.site.register(ForumQuestion)
admin.site.register(Tag)
admin.site.register(Quiz)
admin.site.register(QuizQuestion)
admin.site.register(QuizQuestionChoice)
admin.site.register(RateQuiz)
admin.site.register(TakeQuiz)
admin.site.register(UserAnswer)
admin.site.register(QuizQuestionHint)
admin.site.register(Achievement)
admin.site.register(UserAchievement)
admin.site.register(ForumAnswer)
admin.site.register(ForumBookmark)
admin.site.register(ForumUpvote)
admin.site.register(ForumDownvote)
admin.site.register(ForumAnswerUpvote)
admin.site.register(ForumAnswerDownvote)
admin.site.register(Follow)
admin.site.register(Block)