# Generated by Django 5.0.4 on 2024-05-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20240516_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='picture',
        ),
    ]
