# Generated by Django 5.1.2 on 2024-11-15 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='quizquestionchoice',
            name='choice_number',
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='take_quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.takequiz'),
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='question_number',
        ),
    ]
