# Generated by Django 5.1.2 on 2024-10-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_forumquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('linked_data_id', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='forumquestion',
            name='tag',
        ),
        migrations.AddField(
            model_name='forumquestion',
            name='tag_id',
            field=models.ManyToManyField(to='core.tag'),
        ),
    ]
