# Generated by Django 5.0.4 on 2024-05-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bookmark_unique_together_and_more'),
        ('core', '0002_profile'),
    ]

    operations = [
    ]
