# Generated by Django 5.1.2 on 2024-10-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_remove_forumquestion_tag_forumquestion_tag_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumquestion',
            old_name='tag_id',
            new_name='tags',
        ),
    ]
