# Generated by Django 5.1.2 on 2024-11-17 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumquestion',
            name='parent_question_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.forumquestion'),
        ),
    ]
