# Generated by Django 5.1.2 on 2024-11-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_forumdownvote_forum_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='is_hint_taken',
            field=models.BooleanField(default=False),
        ),
    ]
