# Generated by Django 5.1.2 on 2024-11-17 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_forumquestion_parent_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumquestion',
            name='parent_question_id',
        ),
        migrations.CreateModel(
            name='ForumAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forum_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.forumquestion')),
            ],
        ),
    ]
