# Generated by Django 5.1.2 on 2024-11-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_quiz_quizquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumquestion',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='date',
            new_name='created_at',
        ),
    ]
