# Generated by Django 5.1.2 on 2024-11-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_date_forumquestion_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz_type',
            new_name='type',
        ),
    ]
