# Generated by Django 5.1.2 on 2024-11-21 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_forumanswerdownvote_forumanswerupvote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='takequiz',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='hint_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='hint_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='is_hint_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.quizquestionchoice'),
        ),
    ]
