# Generated by Django 5.1.2 on 2024-11-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_quiz_type_quiz_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='proficiency_level',
            new_name='difficulty',
        ),
    ]
