# Generated by Django 5.1.2 on 2024-11-09 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_proficiency_level_quiz_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestion',
            old_name='correct_answer',
            new_name='answer',
        ),
    ]
