# Generated by Django 5.1.2 on 2024-11-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_quizquestion_hint_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')]),
        ),
    ]
