# Generated by Django 5.1.2 on 2024-11-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_quiz_quiz_point_quizquestion_question_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='takequiz',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
