# Generated by Django 5.1.2 on 2024-11-23 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_takequiz_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumquestion',
            name='quiz_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.quizquestion'),
        ),
    ]
