# Generated by Django 5.1.2 on 2024-11-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_author_takequiz_quiz_taker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takequiz',
            old_name='quiz_taker',
            new_name='quiz_taker_user',
        ),
    ]
