# Generated by Django 5.1.2 on 2024-11-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_forumquestion_quiz_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumquestion',
            old_name='quiz_question',
            new_name='quiz_question_id',
        ),
    ]
