# Generated by Django 5.1.2 on 2024-11-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_quiz_taker_takequiz_quiz_taker_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TakeQuiz',
            new_name='RateQuiz',
        ),
        migrations.RenameField(
            model_name='ratequiz',
            old_name='quiz_taker_user',
            new_name='quiz_rater_user',
        ),
    ]
