# Generated by Django 5.1.2 on 2024-12-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_achievement_customuser_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
