# Generated by Django 5.1.2 on 2024-11-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_quiz_rater_user_ratequiz_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratequiz',
            unique_together={('quiz', 'user')},
        ),
    ]
