# Generated by Django 5.1.2 on 2024-12-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_achievement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumquestion',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
