# Generated by Django 5.1.2 on 2024-11-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_ratequiz_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratequiz',
            unique_together=set(),
        ),
    ]
