# Generated by Django 5.1.2 on 2024-11-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_ratequiz_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratequiz',
            unique_together={('quiz', 'user')},
        ),
    ]
