# Generated by Django 5.1.2 on 2024-12-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_forumquestion_image_url'),
        ('core', '0017_block'),
    ]

    operations = [
    ]
