# Generated by Django 5.1.2 on 2024-12-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_0016_forumquestion_image_url_0017_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='proficiency',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1),
        ),
    ]
