# Generated by Django 5.1.2 on 2024-12-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_0016_forumquestion_image_url_0017_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='proficiency',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='type',
            field=models.IntegerField(choices=[(1, 'English to Turkish'), (2, 'Turkish to English'), (3, 'English word to sense')]),
        ),
    ]
