# Generated by Django 5.1.2 on 2024-11-15 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_ratequiz_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='choices',
        ),
        migrations.CreateModel(
            name='QuizQuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.quizquestion')),
            ],
        ),
    ]
