# Generated by Django 5.1.2 on 2024-11-15 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_ratequiz_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forum_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.forumquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'forum_question')},
            },
        ),
    ]
