# Generated by Django 5.1.2 on 2024-12-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_customuser_proficiency_customuser_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_point',
        ),
        migrations.AddField(
            model_name='ratequiz',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
