# Generated by Django 5.1.2 on 2024-11-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_forumbookmark'),
        ('core', '0019_remove_quizquestion_answer_and_more'),
    ]

    operations = [
    ]
