# Generated by Django 5.1.2 on 2024-12-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_quiz_quiz_point_ratequiz_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
